# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-drag-extension}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dirkkelly"]
  s.date = %q{2010-10-09}
  s.description = %q{Drag pages to sort them}
  s.email = %q{dk@dirkkelly.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "app/views/admin/pages/_drag_order.html.haml",
     "app/views/admin/pages/_drag_order_header.html.haml",
     "config/routes.rb",
     "db/migrate/01_add_position_to_pages.rb",
     "db/migrate/02_add_default_position.rb",
     "drag_extension.rb",
     "lib/drag/controllers/pages_controller.rb",
     "lib/drag/helpers/pages_controller.rb",
     "lib/drag/models/page.rb",
     "lib/drag/tags/core.rb",
     "lib/tasks/drag_extension_tasks.rake",
     "public/images/admin/extensions/drag/.DS_Store",
     "public/images/admin/extensions/drag/circle.png",
     "public/images/admin/extensions/drag/copy.png",
     "public/images/admin/extensions/drag/handle.png",
     "public/javascripts/admin/extensions/drag/drag.js",
     "public/stylesheets/sass/admin/extensions/drag/drag.sass",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/squaretalent/radiant-drag-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Drag Extension for Radiant CMS}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

